### ISSUE TITLE
Function 1 (compute_mass) Testing

### ISSUE THREAD

**Issue by datallurgy** [UBC-MDS/chemcalculator#14]
The tests need to be completed.

**Comment by jo4356** [comment]
`assert compute_mass('(NH4)HS') == pytest.approx(47.079, rel = 1e-3)` is failing.
It is saying that it contains elements not in the periodic table

**Comment by jo4356** [comment]
Test still isnt passing for '(NH4)HS'.
After passing it into `__chemical_elements` it is returning `Counter({'(NH4': 4, 'H': 1, 'S': 1})` (extra starting bracket in front of NH4)

I think the (NH4) is not getting caught in the block
```
# separate compounds from simple elements
    for component in primary_list:
        if re.match('\(.*?\)\d+', component):
            compound_list.append(component)
            primary_list.remove(component)
```
because it doesn't have a number behind it

**Comment by Kingslin0810** [comment]
testing resolved
