### ISSUE TITLE
Function2: moles_grams_converter

### ISSUE THREAD

**Issue by Kingslin0810** [UBC-MDS/chemcalculator#2]
convert moles to grams and grams to moles

**Comment by Kingslin0810** [comment]
added function#2 description in README; 
Reminder: test to ensure chemical formula is input correctly when calling for the function (e.g. needs to be H2O) - if "O2H" is input, the trace error should be "Unable to parse substance formula"

**Comment by Kingslin0810** [comment]
Explanation: this function takes in a chemical formula such as H2O, a float number for the mass of molecule, a string to indicate conversion to be moles or grams, and produces another float number in grams or moles. This function is used to simply answer how many moles H2O in grams, and more friendly it will convert between moles and grams. In chemistry, the formula weight is a quantity computed by multiplying the atomic weight (in atomic mass units) of each element in a chemical formula by the number of atoms of that element present in the formula, then adding all of these products together. A common request on this function is to convert grams to moles or vice versa. To complete this calculation, you have to know what substance (like H2O) you are trying to convert. The reason is that the molar mass of the substance affects the conversion.

**Comment by jo4356** [comment]
We might need to make sure the input is correct for the chemical formula by calling `__check_chemical_format` in this function too.

**Comment by Kingslin0810** [comment]
I thought this part is already tested out in the function#1 but I have added this part of testing in function #2 as on a second thought this testing is necessary. Thanks.
