### ISSUE TITLE
Package overview in Readme and Contributing file 

### ISSUE THREAD

**Issue by Kingslin0810** [UBC-MDS/chemcalculator#5]

**Comment by jo4356** [comment]
- [x] README.md project summary
- [x] README.md function description
- [x] README.md where project fit into Python ecosystem
- [x] CONTRIBUTORS section in README file
- [x] CONDUCT.md

**Comment by datallurgy** [comment]
@Kingslin0810 and @jo4356, please add your function specifications and then I think we can do a final review and submit for Milestone 1.

**Comment by Kingslin0810** [comment]
I added the function#2 description in the README file in my branch <https://github.com/UBC-MDS/chemcalculator/tree/kingslin>
